[package]
name = "atlas-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
atlas-domain = { path = "../atlas-domain" }
atlas-library = { path = "../atlas-library" }
serde_json.workspace = true
sqlx.workspace = true

[dev-dependencies]
lopdf = "0.44.0"
tempfile = "3.27.0"
tokio.workspace = true

[lints]
workspace = true
