[package]
name = "atlas-adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
atlas-domain = { path = "../atlas-domain" }
atlas-reading-session = { path = "../atlas-reading-session" }

[lints]
workspace = true
